### ISSUE TITLE
Side by side installation with stable version

### ISSUE THREAD

**Issue by mkuennek** [dahlia/homebrew-jetbrains-eap#226]
Hi,

I have a question regarding side by side installation with the stable version of rider. I have installed the stable version from the main homebrew channel and now want to try something in the EAP. When trying to install the cask from this repository I get

Error: Cask 'rider-eap' conflicts with 'rider'.

Is there any way to install it side by side like with the Jetbrains Toolbox app?

**Comment by dahlia** [comment]
The reason that the EAP casks managed in this tap repository all have the `conflicts_with` stanza against the regular versions of the casks is simply to mimic the behavior of the [`appcode-eap` cask][1][^1].

Fortunately, all EAP versions of apps are suffixed with <q>EAP</q> in their bundle names, so getting rid of the `conflicts_with` stanza would unlikely actually conflict with the regular versions of the app.

Could you try removing the `conflicts_with` stanza through the command `brew edit --cask dahlia/jetbrains-eap/rider-eap` once, and then install it with `brew install --cask dahlia/jetbrains-eap/rider-eap`? I'd be grateful if you could confirm and report if the installation goes well, and if there are any conflicts with an app already installed with the `rider` cask.

[^1]: It is the only officially managed EAP version of JetBrains app cask in the homebrew-cask-versions repository.

[1]: https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/appcode-eap.rb

**Comment by mkuennek** [comment]
I just tried it. The first start of the EAP was a bit slow but now I have both running in parallel without any noticeable conflicts.

If you want, I opened a Pull Request: https://github.com/dahlia/homebrew-jetbrains-eap/pull/227 Otherwise just disregard it :)
