### ISSUE TITLE
Add binaries to formula

### ISSUE THREAD

**Issue by JakeWharton** [dahlia/homebrew-jetbrains-eap#439]
I launch IntelliJ exclusively from the terminal. With JetBrains Toolbox I was able to have `idea` and `idea-eap` binaries. The regular IntelliJ formula upstream installs an `idea` binary, but these EAP formula do not.

Would you be open to adding binary installation to these?

**Comment by dahlia** [comment]
Of course I'd be happy to add it!  I just don't have the time right now, but if you send me a pull request, I'll review it as soon as I can.
